device_info:
  device:
    name: 1link_robot
  manufacturer:
    name: Nlink_robot
    uuid: e2cba3d4-5fa3-11ed-9b6a-0242ac120001
  model:
    name: 1link_robot
    uuid: e2cba3d4-5fa3-11ed-9b6a-0242ac120002
  user_description: MOTOMAN Robot
  serial_number: 123456789
  device_classes:
    - class_identifier:
        name: robot
        uuid: e2cba3d4-5fa3-11ed-9b6a-0242ac120003
      subclasses: 
        - serial
        - serial_six_axis        
  implemented_types:
    - com.robotraconteur.robotics.robot.Robot
robot_type: serial
robot_capabilities:
- jog_command
- trajectory_command
- position_command
chains:
- kin_chain_identifier: robot_arm
  H:
  - x: 0.0
    y: 0.0
    z: 1.0
  P:
  - x: 0.0
    y: 0.0
    z: 0.0
  - x: 100
    y: 0.0
    z: 0.0
  flange_identifier: tool0
  flange_pose:
    orientation:
      w: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    position:
      x: 0.0
      y: 0.0
      z: 0.0
  joint_numbers:
  - 0
joint_info:
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_1
  joint_limits:
    effort: 1000.0
    lower: -3.14159265
    upper: 3.14159265
    velocity: 3.43829863
    acceleration: 10
  joint_type: revolute
  passive: false
supported_commands:
  - MoveJ
  - MoveL
  - MoveC
  - setWaitTime
  - setArc
  - changeArc