tool_markers:
  marker16_rigid1:
  - 0
  - 0
  - 0
  marker17_rigid1:
  - 0
  - 0
  - 0
  marker18_rigid1:
  - 0
  - 0
  - 0
  marker19_rigid1:
  - 0
  - 0
  - 0
  marker20_rigid1:
  - 0
  - 0
  - 0
  marker21_rigid1:
  - 0
  - 0
  - 0
  marker22_rigid1:
  - 0
  - 0
  - 0
  marker23_rigid1:
  - 0
  - 0
  - 0
